[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false
rust-version = "1.64.0"
authors = ["Piper Merriam <piper@pipermerriam.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
chrono = "0.4.22"
enr = "0.7.0"
ethereum-types = "0.14.0"
ethportal-api = "0.1.3"
glados-core = { path = "../glados-core" }
hex = "0.4.3"
migration = { path = "../migration" }
sea-orm = { version = "0.10.1", features = ["sqlx-postgres", "sqlx-sqlite", "macros", "runtime-tokio-native-tls"] }
tokio = { version = "1.21.2", features = ["macros"] }

[dev-dependencies]
hex = "0.4.3"
