[package]
name = "glados-web"
version = "0.1.0"
edition = "2021"
publish = false
rust-version = "1.64.0"
authors = ["Piper Merriam <piper@pipermerriam.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glados-core = { path = "../glados-core" }
migration = { path = "../migration" }
entity = { path = "../entity" }
askama = "0.11.1"
axum = "0.6.1"
sea-orm = "0.10.2"
ethereum-types = "0.14.0"
tokio = "1.22.0"
clap = { version = "4.0.26", features = ["derive"] }
tower-http = { version = "0.3.5", features = ["fs"] }
hex = "0.4.3"
